name: fandom
description: A library for Fandom APIv1 interaction, which makes it easy to access data from specified fandom URL
version: 1.0.0
homepage: https://github.com/materka/fandom

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  json_serializable: ^3.3.0
  effective_dart: ^1.2.0
  test: ^1.14.4
  http: ^0.12.2
  dio: ^3.0.9
  build_runner: ^1.0.0
